#!/usr/bin/env bash

pacstrap /mnt base base-devel linux-zen linux-firmware texinfo inetutils networkmanager \
              perl man-db man-pages diffutils less nano vi vim sysfsutils \
              e2fsprogs dosfstools ntfs-3g usbutils which logrotate reflector git \
              bash-completion intel-ucode
